### ISSUE TITLE
Auth seems to be broken now as 3 legged auth required (password grant deprecated).

### ISSUE THREAD

**Issue by bwghughes** [simonvc/mondo-python#8]
When I try as per the docs, I get:

```
Traceback (most recent call last):
  File "bitbar.py", line 7, in <module>
    u'xxxxxxxxxxxxxxxxxxxxxxxxxx')
  File "build/bdist.macosx-10.11-x86_64/egg/mondo/__init__.py", line 46, in __init__
Exception: 400: Bad Req. Your request has missing parameters or is malformed
```

**Comment by marrold** [comment]
I'm having the same issue.
